## Q2. 

Download a YouTube spam collection dataset available from this link (Links to an external site.).

This is a public set of comments collected for spam research. It has five datasets composed by 1,956 real messages extracted from five videos. These 5 videos are popular pop songs that were among the 10 most viewed on the collection period.
All the five dataset has the following attributes:

COMMENT_ID: Unique id representing the comment  
AUTHOR: Author id,  
DATE: Date the comment is posted,  
CONTENT: The comment,  
TAG: For spam 1, otherwise 0

For this exercise use any 4 of these 5 datasets to build a spam filter with Naive Bayes approach and use that filter to check the accuracy on the remaining dataset. Make sure to report the details of your training and the model. [6 points]

### import packages

In [1]:
import os, glob

import numpy as np
import pandas as pd

import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline

### read data

#### For this exercise use any four of these five datasets to build a spam filter with the Naïve Bayes approach.

In [2]:
train_df = pd.DataFrame()

#Read data
files = glob.glob("./YouTube-Spam-Collection-v1/*")
files = sorted(files)[:-1]
for f in files:
    temp = pd.read_csv(f)
    print("(file, shape):", f, temp.shape)
    train_df = train_df.append(temp, ignore_index=True)
print("the shape of training files", train_df.shape)
#Pick necessary columns
train_df = train_df[['CONTENT', 'CLASS']]
#train_df['CONTENT'] = train_df['CONTENT'].apply(textcleaner)
train_df.head(50)

(file, shape): ./YouTube-Spam-Collection-v1/Youtube01-Psy.csv (350, 5)
(file, shape): ./YouTube-Spam-Collection-v1/Youtube02-KatyPerry.csv (350, 5)
(file, shape): ./YouTube-Spam-Collection-v1/Youtube03-LMFAO.csv (438, 5)
(file, shape): ./YouTube-Spam-Collection-v1/Youtube04-Eminem.csv (448, 5)
the shape of training files (1586, 5)

/var/folders/nl/0t1qmzl174xchcymt5p1_p0w0000gn/T/ipykernel_2084/1049936703.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_df = train_df.append(temp, ignore_index=True)
/var/folders/nl/0t1qmzl174xchcymt5p1_p0w0000gn/T/ipykernel_2084/1049936703.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_df = train_df.append(temp, ignore_index=True)
/var/folders/nl/0t1qmzl174xchcymt5p1_p0w0000gn/T/ipykernel_2084/1049936703.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_df = train_df.append(temp, ignore_index=True)
/var/folders/nl/0t1qmzl174xchcymt5p1_p0w0000gn/T/ipykernel_2084/1049936703.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_df = train_df.append(temp, ignore_index=True)

                                              CONTENT  CLASS
0   Huh, anyway check out this you[tube] channel: ...      1
1   Hey guys check out my new channel and our firs...      1
2              just for test I have to say murdev.com      1
3    me shaking my sexy ass on my channel enjoy ^_^ ﻿      1
4             watch?v=vtaRGgvGtWQ   Check this out .﻿      1
5   Hey, check out my new website!! This site is a...      1
6                           Subscribe to my channel ﻿      1
7   i turned it on mute as soon is i came on i jus...      0
8     You should check my channel for Funny VIDEOS!!﻿      1
9   and u should.d check my channel and tell me wh...      1
10                               Hey subscribe to me﻿      1
11   Once you have started reading do not stop. If...      1
12               https://twitter.com/GBphotographyGB﻿      1
13                            subscribe like comment﻿      1
14  please like :D https://premium.easypromosapp.c...      1
15  Hello! Do you like gaming, art videos, scienti...      1
16                       I'm only checking the views﻿      0
17  http://www.ebay.com/itm/171183229277?ssPageNam...      1
18       http://ubuntuone.com/40beUutVu2ZKxK4uTgPZ8K﻿      1
19  We are an EDM apparel company dedicated to bri...      1
20  i think about 100 millions of the views come f...      0
21                 subscribe to my channel people :D﻿      1
22  Show your AUBURN PRIDE HERE: http://www.teespr...      1
23                           just checking the views﻿      0
24                               CHECK OUT MY CHANNEL      1
25  marketglory . com/strategygame/andrijamatf ear...      1
26  Hey guys! Im a 12 yr old music producer. I mak...      1
27            Check me out! I'm kyle. I rap so yeah ﻿      1
28  I dont even watch it anymore i just come here ...      0
29   Subscribe to me for free Android games, apps.. ﻿      1
30  everyone please come check our newest song in ...      1
31            Came here to check the views, goodbye.﻿      0
32                  sub my channel for no reason -_-﻿      1
33  Check out my dubstep song "Fireball", made wit...      1
34                          2 billion....Coming soon﻿      0
35  Why dafuq is a Korean song so big in the USA. ...      0
36  Check my channel please! And listen to the bes...      1
37  SUB 4 SUB PLEASE LIKE THIS COMMENT I WANT A SU...      1
38   Hey everyone!! I have just started my first Y...      1
39  The projects After Effects, Music, Foto, Web s...      1
40  YouTube/codytolleson for awesome videos I'll s...      1
41  if you like roblox minecraft world of warcraft...      1
42  SUBSCRIBE TO ME AND I'LL SUBSCRIBE TO YOU! (Mu...      1
43  http://www.twitch.tv/jaroadc come follow and w...      1
44  if you like raw talent, raw lyrics, straight r...      1
45  ....subscribe......  ......to my........  .......      1
46  now its 1,884,034,783 views! pls. comment the ...      0
47  http://www.avaaz.org/po/petition/Youtube_Corpo...      1
48                     go here to check the views :3﻿      0
49  thumbs up if u checked this video to see hw vi...      0

In [3]:
test_df = pd.read_csv('./YouTube-Spam-Collection-v1/Youtube05-Shakira.csv')
print("the shape of the test dataset", test_df.shape)
test_df = test_df[['CONTENT', 'CLASS']]
#test_df['CONTENT'] = test_df['CONTENT'].apply(textcleaner)
test_df.head(50)

the shape of the test dataset (370, 5)

                                              CONTENT  CLASS
0                                          Nice song﻿      0
1                                       I love song ﻿      0
2                                       I love song ﻿      0
3   860,000,000 lets make it first female to reach...      0
4                       shakira is best for worldcup﻿      0
5                   The best world cup song ever!!!!﻿      0
6                                             I love﻿      0
7   SEE SOME MORE SONG OPEN GOOGLE AND TYPE Shakir...      1
8                                           Awesome ﻿      0
9                                   I like shakira..﻿      0
10  Shakira - Waka Waka <br />LOVE THIS SONG!!!!!!...      0
11                 Why so many disliked??????!!!!!!😯﻿      0
12    I don&#39;t think this song will ever get old ﻿      0
13                                         Love song﻿      0
14                                         wery good﻿      0
15  Every time I hear this song, I think about Ini...      0
16           Whose watching this in 2015. If so hi-5﻿      0
17  I love this song so much &lt;3<br />Keep em&#3...      0
18                 i love this song thumsb up to you﻿      0
19                                     Waka best one﻿      0
20  5 years later i still love this song <br />~Ax...      0
21                                              Like﻿      0
22               Check out this playlist on YouTube:﻿      1
23  Her voice sounds weird and plus she&#39;s cute...      0
24  Why there are so many dislikes. This song is s...      0
25  Nice love itttttttt wurkkkkkkkkkkkkkkkkkkkkkkk...      0
26                         still watching in 2015...﻿      0
27            Shakira is my favourite singer. Wooooo﻿      0
28                              i remember this song!      0
29                                              Like﻿      0
30       Whose who are watching this in 2015.  LIKE!﻿      0
31  Support the fight for your 4th amendment right...      1
32                                best song in world﻿      0
33                                          BEAUTIFUL      0
34                                      Good song:-)﻿      0
35  She&#39;s such an awesome entertainer. And pre...      0
36                  Check out this video on YouTube:﻿      1
37                                    Love this song﻿      0
38  Love this song! My soccer team made a cd for o...      0
39                                         fave song﻿      0
40                                  Watching in 2015﻿      0
41  I felt old when I realized that this song was ...      0
42                                     love Shakira!﻿      0
43              One of the best song of all the time﻿      0
44       I really am madly in love with this woman!!﻿      0
45  i totally love this song. absolutely fantastic...      0
46                         im still watching in 2015﻿      0
47                                   the song is sad﻿      0
48                                             goood﻿      0
49            The best FIFA world cup song for sure.﻿      0

In [4]:
def textcleaner(row):
    row = row.lower()     
    row = re.sub("[^\w\s']", "", row) # remove punctuations
    row = row.strip(" ")
    return row

In [5]:
test_df = pd.read_csv('./YouTube-Spam-Collection-v1/Youtube05-Shakira.csv')
print("the shape of the test dataset", test_df.shape)
test_df = test_df[['CONTENT', 'CLASS']]
test_df['CONTENT'] = test_df['CONTENT'].apply(textcleaner)
test_df.head(50)

the shape of the test dataset (370, 5)

                                              CONTENT  CLASS
0                                           nice song      0
1                                         i love song      0
2                                         i love song      0
3   860000000 lets make it first female to reach o...      0
4                        shakira is best for worldcup      0
5                        the best world cup song ever      0
6                                              i love      0
7   see some more song open google and type shakir...      1
8                                             awesome      0
9                                      i like shakira      0
10               shakira  waka waka br love this song      0
11                               why so many disliked      0
12         i don39t think this song will ever get old      0
13                                          love song      0
14                                          wery good      0
15  every time i hear this song i think about inie...      0
16              whose watching this in 2015 if so hi5      0
17    i love this song so much lt3br keep em39 coming      0
18                  i love this song thumsb up to you      0
19                                      waka best one      0
20     5 years later i still love this song br axy665      0
21                                               like      0
22                 check out this playlist on youtube      1
23  her voice sounds weird and plus she39s cute fo...      0
24  why there are so many dislikes this song is so...      0
25  nice love itttttttt wurkkkkkkkkkkkkkkkkkkkkkkk...      0
26                             still watching in 2015      0
27              shakira is my favourite singer wooooo      0
28                               i remember this song      0
29                                               like      0
30          whose who are watching this in 2015  like      0
31  support the fight for your 4th amendment right...      1
32                                 best song in world      0
33                                          beautiful      0
34                                          good song      0
35  she39s such an awesome entertainer and pretty ...      0
36                    check out this video on youtube      1
37                                     love this song      0
38  love this song my soccer team made a cd for ou...      0
39                                          fave song      0
40                                   watching in 2015      0
41  i felt old when i realized that this song was ...      0
42                                       love shakira      0
43               one of the best song of all the time      0
44          i really am madly in love with this woman      0
45  i totally love this song absolutely fantastic ...      0
46                          im still watching in 2015      0
47                                    the song is sad      0
48                                              goood      0
49              the best fifa world cup song for sure      0

In [6]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(train_df['CONTENT'])
vectorizer.get_feature_names_out()

array(['00', '000', '002', ..., 'ｆａｎｃy', 'ｉｓ', 'ｔｈｉｓ'], dtype=object)

In [7]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

### apply Naive Bayes approach

In [10]:
#Create a data pipeline
pipeline = Pipeline([
    ('bow', CountVectorizer()),  # strings to token integer counts
   # ('tfidf', TfidfTransformer(use_idf=True, smooth_idf=True)),  # integer counts to weighted TF-IDF scores
    ('classifier', MultinomialNB()),  # train on TF-IDF vectors w/ Naive Bayes classifier
])

In [11]:
#Fit the training data
pipeline.fit(train_df['CONTENT'],train_df['CLASS'])

Pipeline(steps=[('bow', CountVectorizer()), ('classifier', MultinomialNB())])

#### Use that filter to check the accuracy of the remaining dataset.

In [12]:
#Predict on the testing data
predictions = pipeline.predict(test_df['CONTENT'])

#Print the classification report and accuracy score
print(classification_report(predictions,test_df['CLASS']))
print("accuracy:", round(accuracy_score(predictions,test_df['CLASS']), 4))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88       186
           1       0.90      0.85      0.87       184

    accuracy                           0.88       370
   macro avg       0.88      0.88      0.88       370
weighted avg       0.88      0.88      0.88       370

accuracy: 0.8757

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
# Multiple documents
tweet = ["Next I'm buying Coca-Cola to put the cocaine back in"] 
# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(tweet)
# summarize
print(sorted(vectorizer.vocabulary_))

['back', 'buying', 'coca', 'cocaine', 'cola', 'in', 'next', 'put', 'the', 'to']

In [14]:
# encode document
vector = vectorizer.transform(tweet)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(1, 10)
[[1 1 1 1 1 1 1 1 1 1]]