In this exercise you will use the Portuguese sea battles data (Links to an external site.) that contains outcomes of naval battles between Portuguese and Dutch/British ships between 1583 and 1663. The dataset has following features:

- Battle: Name of the battle place
- Year: Year of the battle
- Portuguese ships: Number of Portuguese ships
- Dutch ships: Number of Dutch ships
- English ships: Number of ships from English side
- Ratio of Portuguese to Dutch/British ships
- Spanish Involvement: 1=Yes, 0=No
- Portuguese outcome: -1=Defeat, 0=Draw, 1=Victory

Use an SVM based model to predict the Portuguese outcome of the battle from the number of ships involved in all sides and Spanish involvement. Try solving the same problem using two other classifiers that you know. Report and compare their results with those from SVM.

### import packages

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
import warnings
warnings.filterwarnings('ignore')

### read data

In [16]:
cols = ['Battle', 'Year', 'PortugeseShips', 'DutchShips', 'EnglishShips', 'Ratio', 
        'SpanishInvolvement', 'PortugeseOutcome']
df = pd.read_csv("http://users.stat.ufl.edu/~winner/data/armada.dat", sep=r'\s{2,}', 
                 names = cols, header = None)
df.head()

,Battle,Year,PortugeseShips,DutchShips,EnglishShips,Ratio,SpanishInvolvement,PortugeseOutcome
0,Bantam,1601,6,3,0,2.000,0,0
1,Malacca Strait,1606,14,11,0,1.273,0,0
2,Ilha das Naus,1606,6,9,0,0.667,0,-1
3,Pulo Butum,1606,7,9,0,0.778,0,1
4,Surrat,1615,6,0,4,1.500,0,0

In [17]:
#Creating X and y
X = df.iloc[:, [2,3,4,6]]
y = df[['PortugeseOutcome']]

#Creating training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [18]:
df['PortugeseOutcome'].unique()

array([ 0, -1,  1])

### Apply different classification algorithms

#### SVC

In [19]:
#Building the SVC model and fitting the training data
svc_model = SVC(kernel='linear')
svc_model.fit(X_train,y_train.values.ravel())

#Predicting on the test data
predictions = svc_model.predict(X_test)

#Printing the accuracy
svc_accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", svc_accuracy)
#Printing the confusion matrix
print(confusion_matrix(y_test,predictions))
#Printing the classification report
print(classification_report(y_test,predictions))

Accuracy: 0.2857142857142857
[[2 0 0]
 [2 0 1]
 [0 2 0]]
              precision    recall  f1-score   support

          -1       0.50      1.00      0.67         2
           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00         2

    accuracy                           0.29         7
   macro avg       0.17      0.33      0.22         7
weighted avg       0.14      0.29      0.19         7

#### Logisitic Regression model

In [20]:
#Creating Logisitic Regression model
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train,y_train)

#Predicting on Test set
predictions = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, predictions)
print(lr_accuracy)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test, predictions))

0.14285714285714285
[[1 1 0]
 [2 0 1]
 [0 2 0]]
              precision    recall  f1-score   support

          -1       0.33      0.50      0.40         2
           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00         2

    accuracy                           0.14         7
   macro avg       0.11      0.17      0.13         7
weighted avg       0.10      0.14      0.11         7

#### KNN

In [21]:
#Creating KNN Classfier model
knn = KNeighborsClassifier(n_neighbors=3)

#Fitting the training data
knn.fit(X_train,y_train)

#Predicting on the test data
predictions = knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, predictions)
print("k=", 3)
#Printing Confusion matrix and accuracy socres 
print(accuracy_score(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test, predictions))

k= 3
0.42857142857142855
[[2 0 0]
 [2 1 0]
 [1 1 0]]
              precision    recall  f1-score   support

          -1       0.40      1.00      0.57         2
           0       0.50      0.33      0.40         3
           1       0.00      0.00      0.00         2

    accuracy                           0.43         7
   macro avg       0.30      0.44      0.32         7
weighted avg       0.33      0.43      0.33         7

#### decision tree

In [22]:
# Creating the DTC and fitting the model
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

#Predicting on test data
predictions = dtree.predict(X_test)
dtree_accuracy = accuracy_score(y_test, predictions)
#Printing the classification report and accuracy score
print(accuracy_score(y_test,predictions))
print(confusion_matrix(y_test,predictions))

0.2857142857142857
[[1 1 0]
 [1 1 1]
 [0 2 0]]

#### random forest

In [23]:
rfc = RandomForestClassifier(n_estimators=100)
# y_train is a column vector, but 1d array is expected. Therefore, we need to
# change the shape to (n_samples,)
rfc.fit(X_train, y_train.values.ravel())
predictions = rfc.predict(X_test)
rfc_accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy_score(y_test, predictions))
print(confusion_matrix(y_test,predictions))

Accuracy: 0.42857142857142855
[[1 1 0]
 [1 2 0]
 [0 2 0]]

In [24]:
print(f"Logistic Regression Accuracy: {lr_accuracy}")
print(f"SVC Accuracy: {svc_accuracy}")
print(f"KNN Accuracy: {knn_accuracy}")
print(f"Decision Tree Accuracy: {dtree_accuracy}")
print(f"Random Forest Accuracy: {rfc_accuracy}")

Logistic Regression Accuracy: 0.14285714285714285
SVC Accuracy: 0.2857142857142857
KNN Accuracy: 0.42857142857142855
Decision Tree Accuracy: 0.2857142857142857
Random Forest Accuracy: 0.42857142857142855

In [25]:
# For SVM
svm_train_acc = svc_model.score(X_train, y_train)
svm_test_acc = svc_accuracy  # You already calculated this

# For Logistic Regression
logreg_train_acc = lr_model.score(X_train, y_train)
logreg_test_acc = lr_accuracy  # You already calculated this

# For Decision Tree
dt_train_acc = dtree.score(X_train, y_train)
dt_test_acc = dtree_accuracy  # You already calculated this

# Create a comparison DataFrame
import pandas as pd
acc_comparison = pd.DataFrame({
    'Model': ['SVM', 'Logistic Regression', 'Decision Tree'],
    'Training Accuracy': [svm_train_acc, logreg_train_acc, dt_train_acc],
    'Test Accuracy': [svm_test_acc, logreg_test_acc, dt_test_acc]
})

acc_comparison

                 Model  Training Accuracy  Test Accuracy
0                  SVM           0.714286       0.285714
1  Logistic Regression           0.761905       0.142857
2        Decision Tree           1.000000       0.285714